resources:
- di_operator.yaml
- di_server.yaml
- di_webhook.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: diorchestrator/di-operator
  newName: diorchestrator/di-operator
  newTag: v0.2.0-rc.0
- name: diorchestrator/di-server
  newName: diorchestrator/di-server
  newTag: v0.2.0-rc.0
- name: diorchestrator/di-webhook
  newName: diorchestrator/di-webhook
  newTag: v0.2.0-rc.0
