resources:
- di_operator.yaml
- di_server.yaml
- di_webhook.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: opendilab/di-orchestrator/di-operator
  newName: opendilab/di-orchestrator/di-operator
  newTag: v0.2.0
- name: opendilab/di-orchestrator/di-server
  newName: opendilab/di-orchestrator/di-server
  newTag: v0.2.0
- name: opendilab/di-orchestrator/di-webhook
  newName: opendilab/di-orchestrator/di-webhook
  newTag: v0.2.0
